<?php
/** @var array $types @var array $reports @var array $filters */
$types = $types ?? [];
$reports = $reports ?? [];
$filters = $filters ?? [];
$programs = $filters['programs'] ?? [];
$batches = $filters['batches'] ?? [];
?>
<div class="space-y-6">

    <div>
        <h2 class="text-xl font-bold text-ink-900">Reports</h2>
        <p class="text-sm text-ink-500">Generate and download PDF, Excel and CSV reports</p>
    </div>

    <!-- Generate form -->
    <div class="card">
        <div class="card-header"><h3 class="font-semibold text-ink-800">Generate Report</h3></div>
        <div class="card-body">
            <form method="POST" action="<?= url('admin/reports/generate') ?>" class="grid grid-cols-1 md:grid-cols-4 gap-3 items-end">
                <?= csrf_field() ?>
                <div>
                    <label class="label" for="r-type">Report Type</label>
                    <select name="type" id="r-type" class="input" onchange="updateFormats(this.value)">
                        <?php foreach ($types as $key => $meta): ?>
                            <option value="<?= e($key) ?>"><?= e($meta['label']) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label class="label" for="r-format">Format</label>
                    <select name="format" id="r-format" class="input">
                        <option value="pdf">PDF</option>
                        <option value="excel">Excel</option>
                        <option value="csv">CSV</option>
                    </select>
                </div>
                <div>
                    <label class="label" for="r-program">Program (optional)</label>
                    <select name="program_id" id="r-program" class="input">
                        <option value="">All Programs</option>
                        <?php foreach ($programs as $p): ?>
                            <option value="<?= (int) $p['id'] ?>"><?= e($p['name']) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label class="label" for="r-batch">Batch (optional)</label>
                    <select name="batch_id" id="r-batch" class="input">
                        <option value="">All Batches</option>
                        <?php foreach ($batches as $b): ?>
                            <option value="<?= (int) $b['id'] ?>"><?= e($b['label'] ?? $b['year']) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="md:col-span-4 flex justify-end">
                    <button type="submit" class="btn-primary"><i data-lucide="file-down" class="w-4 h-4"></i> Generate</button>
                </div>
            </form>
        </div>
    </div>

    <!-- Generated reports -->
    <div class="card">
        <div class="card-header"><h3 class="font-semibold text-ink-800">Generated Reports</h3></div>
        <div class="table-wrap">
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Type</th>
                        <th>Format</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th class="text-right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php if (empty($reports)): ?>
                    <tr><td colspan="6" class="!text-center !py-10 text-ink-500">No reports generated yet.</td></tr>
                <?php endif; ?>
                <?php foreach ($reports as $r): ?>
                    <tr>
                        <td class="font-medium text-ink-800"><?= e($r['title']) ?></td>
                        <td><span class="badge-blue"><?= e(ucwords(str_replace('_', ' ', $r['type']))) ?></span></td>
                        <td><span class="badge-<?= $r['format'] === 'pdf' ? 'red' : ($r['format'] === 'excel' ? 'green' : 'amber') ?>"><?= e(strtoupper($r['format'])) ?></span></td>
                        <td><?= e($r['generated_by_name'] ?? 'System') ?></td>
                        <td><?= date('M j, Y g:i A', strtotime($r['generated_at'])) ?></td>
                        <td class="text-right">
                            <div class="flex items-center justify-end gap-1">
                                <a href="<?= url('admin/reports/' . (int) $r['id'] . '/download') ?>" class="btn-secondary !py-1.5 !px-3 text-xs"><i data-lucide="download" class="w-3.5 h-3.5"></i> Download</a>
                                <form method="POST" action="<?= url('admin/reports/' . (int) $r['id']) ?>" onsubmit="return confirmAction('Delete this report?', this);">
                                    <?= csrf_field() ?>
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" class="icon-btn !text-red-600 hover:!bg-red-50" title="Delete"><i data-lucide="trash-2" class="w-4 h-4"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php
$formats = [];
foreach ($types as $key => $meta) {
    $formats[$key] = $meta['formats'];
}
$scripts = '<script>
    var reportFormats = ' . json_encode($formats) . ';
    function updateFormats(type) {
        var sel = document.getElementById("r-format");
        var allowed = reportFormats[type] || ["pdf"];
        Array.prototype.forEach.call(sel.options, function (o) {
            o.disabled = allowed.indexOf(o.value) === -1;
            if (o.disabled && o.selected) { sel.value = allowed[0]; }
        });
    }
    window.addEventListener("DOMContentLoaded", function () {
        var first = document.getElementById("r-type");
        if (first) updateFormats(first.value);
    });
</script>';
