<?php
/** @var array $report */
$report = $report ?? [];
?>
<div class="space-y-6">
    <div>
        <h2 class="text-xl font-bold text-ink-900"><?= e($report['title'] ?? 'Report') ?></h2>
        <p class="text-sm text-ink-500">Generated by <?= e($report['generated_by_name'] ?? 'System') ?> on <?= date('M j, Y g:i A', strtotime($report['generated_at'])) ?></p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div class="kpi-card">
            <p class="text-2xl font-bold text-ink-900"><?= e(strtoupper($report['format'])) ?></p>
            <p class="text-xs text-ink-500">Format</p>
        </div>
        <div class="kpi-card">
            <p class="text-2xl font-bold text-ink-900"><?= e(ucwords(str_replace('_', ' ', $report['type']))) ?></p>
            <p class="text-xs text-ink-500">Report Type</p>
        </div>
        <div class="kpi-card">
            <p class="text-2xl font-bold text-ink-900">
                <?php
                $file = (string) config('app.paths.storage_exports') . '/' . $report['file_path'];
                $size = is_file($file) ? filesize($file) : 0;
                echo $size >= 1048576 ? number_format($size / 1048576, 2) . ' MB' : number_format($size / 1024, 1) . ' KB';
                ?>
            </p>
            <p class="text-xs text-ink-500">File Size</p>
        </div>
    </div>

    <?php if (!empty($report['filters'])): ?>
        <?php $filters = json_decode((string) $report['filters'], true) ?: []; ?>
        <?php if ($filters): ?>
            <div class="card">
                <div class="card-header"><h3 class="font-semibold text-ink-800">Filters Applied</h3></div>
                <div class="card-body flex flex-wrap gap-2">
                    <?php foreach ($filters as $key => $value): ?>
                        <span class="badge-gray"><?= e(ucwords(str_replace('_', ' ', (string) $key))) ?>: <?= e((string) $value) ?></span>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <div class="flex gap-2">
        <a href="<?= url('admin/reports/' . (int) $report['id'] . '/download') ?>" class="btn-primary"><i data-lucide="download" class="w-4 h-4"></i> Download Report</a>
        <a href="<?= url('admin/reports') ?>" class="btn-secondary"><i data-lucide="arrow-left" class="w-4 h-4"></i> Back to Reports</a>
    </div>
</div>
