<?php
/** @var array $indicators @var array $benchmarks @var array $models @var int $target */
$indicators = $indicators ?? [];
$benchmarks = $benchmarks ?? [];
$models = $models ?? [];
$target = $target ?? 70;
?>
<div class="space-y-6">

    <div class="flex flex-wrap items-center justify-between gap-3">
        <div>
            <h2 class="text-xl font-bold text-ink-900">Forecasting</h2>
            <p class="text-sm text-ink-500">Generate employment projections using linear regression</p>
        </div>
        <span id="benchmark-badge" class="badge-blue">Employment target: <?= (int) $target ?>%</span>
    </div>

    <!-- Generate form -->
    <form method="POST" action="<?= url('admin/forecasting/generate') ?>" class="card p-4 flex flex-wrap items-end gap-3">
        <?= csrf_field() ?>
        <div>
            <label class="label" for="f-indicator">Indicator</label>
            <select name="indicator" id="f-indicator" class="input !w-72">
                <?php foreach ($indicators as $key => $meta): ?>
                    <option value="<?= e($key) ?>" <?= $key === 'employment_rate' ? 'selected' : '' ?>><?= e($meta['label']) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label class="label" for="f-years">Years Ahead (1–5)</label>
            <input type="number" name="years_ahead" id="f-years" min="1" max="5" value="3" class="input !w-28">
        </div>
        <button type="submit" class="btn-primary"><i data-lucide="trending-up" class="w-4 h-4"></i> Generate Forecast</button>
    </form>

    <!-- Saved models -->
    <div class="card">
        <div class="card-header"><h3 class="font-semibold text-ink-800">Saved Forecast Models</h3></div>
        <div class="table-wrap">
            <table class="table">
                <thead>
                    <tr>
                        <th>Indicator</th>
                        <th>History</th>
                        <th>Projection</th>
                        <th>Slope</th>
                        <th>R²</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th class="text-right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                <?php if (empty($models)): ?>
                    <tr><td colspan="8" class="!text-center !py-10 text-ink-500">No forecast models yet. Generate your first forecast above.</td></tr>
                <?php endif; ?>
                <?php foreach ($models as $m): ?>
                    <tr>
                        <td class="font-medium text-ink-800"><?= e($m['indicator_label']) ?></td>
                        <td>
                            <?php if ($m['historical_start']): ?>
                                <?= (int) $m['historical_start'] ?>–<?= (int) $m['historical_end'] ?>
                                <span class="text-xs text-ink-400">(<?= (int) $m['observations'] ?> obs)</span>
                            <?php else: ?>
                                <span class="text-ink-400">—</span>
                            <?php endif; ?>
                        </td>
                        <td>
                            <?php if ($m['forecast_start']): ?>
                                <?= (int) $m['forecast_start'] ?>–<?= (int) $m['forecast_end'] ?>
                            <?php else: ?>
                                <span class="text-ink-400">—</span>
                            <?php endif; ?>
                        </td>
                        <td><?= $m['slope'] !== null ? $m['slope'] : '—' ?></td>
                        <td>
                            <?php if ($m['r_squared'] !== null): ?>
                                <span class="badge-<?= $m['r_squared'] >= 0.3 ? 'green' : 'amber' ?>"><?= $m['r_squared'] ?></span>
                            <?php else: ?>
                                <span class="badge-gray">—</span>
                            <?php endif; ?>
                        </td>
                        <td><?= e($m['created_by_name'] ?? 'System') ?></td>
                        <td><?= date('M j, Y g:i A', strtotime($m['created_at'])) ?></td>
                        <td class="text-right">
                            <div class="flex items-center justify-end gap-1">
                                <a href="<?= url('admin/forecasting/' . (int) $m['id']) ?>" class="icon-btn" title="View"><i data-lucide="eye" class="w-4 h-4"></i></a>
                                <form method="POST" action="<?= url('admin/forecasting/' . (int) $m['id']) ?>" onsubmit="return confirmAction('Delete this forecast model?', this);">
                                    <?= csrf_field() ?>
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button type="submit" class="icon-btn !text-red-600 hover:!bg-red-50" title="Delete"><i data-lucide="trash-2" class="w-4 h-4"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var select = document.getElementById('f-indicator');
        var badge = document.getElementById('benchmark-badge');
        if (!select || !badge) return;
        var map = <?= json_encode($benchmarks, JSON_UNESCAPED_UNICODE) ?>;
        function update() {
            var b = map[select.value] || null;
            if (b) {
                badge.textContent = b.label + ': ' + b.value;
                badge.classList.remove('hidden');
            } else {
                badge.classList.add('hidden');
            }
        }
        select.addEventListener('change', update);
        update();
    });
</script>
